name: 🎇 Update Repository

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to update to (like 0.1.16)
        type: string
        default: ''
        required: true

jobs:
  update:
    if: inputs.version != ''
    name: UpdateRepository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: update version
        run: |
          sed -i 's/"version": "[^"]*"/"version": "0.1.16"/' package.json
          cd submodules/univer
          git checkout v${{ inputs.version}}
          git pull

      - name: UpdateRepository
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            echo 'skip'
          COMMIT_MESSAGE: 'chore(release): v${{ inputs.version }}'
          COMMIT_NAME: GitHub Actions
          PR_BRANCH_PREFIX: chore/
          PR_BRANCH_NAME: 'update-release-${PR_ID}'
          PR_TITLE: 'chore(release): v${{ inputs.version }}'
