name: 🎇 Sync Univer version

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to update to (like 0.1.16)
        type: string
        default: ''
        required: true

jobs:
  update:
    if: inputs.version != ''
    name: UpdateRepository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: update version
        run: |
          cd submodules/univer
          git checkout v${{ inputs.version}}

      - name: UpdateRepository
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            sed -i 's/"version": "[^"]*"/"version": "0.1.16"/' package.json
          COMMIT_MESSAGE: 'chore(release): sync univer to v${{ inputs.version }}'
          COMMIT_NAME: GitHub Actions
          PR_BRANCH_PREFIX: chore/
          PR_BRANCH_NAME: 'sync-univer-to-v${{ inputs.version }}'
          PR_TITLE: 'chore(release): sync univer to v${{ inputs.version }}'
