name: 🎇 Update Repository

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to update to (like 0.1.16)
        type: string
        default: ''
        required: true

jobs:
  update:
    name: UpdateRepository
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: UpdateRepository
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            npm version ${{ inputs.version }} --no-git-tag-version
            cd univer-typedoc/submodules/univer
            git checkout v${{ inputs.version}}
          COMMIT_MESSAGE: 'chore(release): v${{ inputs.version }}'
          COMMIT_NAME: GitHub Actions
          PR_BRANCH_PREFIX: create-pr-action/
          PR_BRANCH_NAME: 'update-repository-${PR_ID}'
          PR_TITLE: 'chore: update repository'
