name: 📤 Deploy Staging

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: The image tag to deploy (optional, if not provided, the image will be built first)
        type: string
        default: ''
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: inputs.image-tag == ''
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    if: inputs.image-tag == ''
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: dream-num/helm-chart-private
          event-type: dispatch
          client-payload: '{"service":"univer-typedoc","tag":"${{ needs.build.outputs.image-tag }}"}'

  deploy-trigger:
    if: inputs.image-tag != ''
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: dream-num/helm-chart-private
          event-type: dispatch
          client-payload: '{"service":"univer-typedoc","tag":"${{ inputs.image-tag }}"}'
