name: 📤 Deploy Staging

on:
  workflow_dispatch:
  branch:
    - ci/deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    runs-on: arc-runner-set
    needs: build
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: dream-num/helm-chart-private
          event-type: dispatch
          client-payload: '{"service":"univer-typedoc","tag":"${{ needs.build.outputs.image-tag }}"}'
